name: Report a bug
title: "[bug] ..."
description: Create a report to help us improve Bark.
labels: ["bug", "problem"]
body:
- type: markdown
  attributes:
    - value: "## Thanks for filling out this report!"

- type: checkboxes
  id: os
  attributes:
    label: Operating System
    description: "What operating system(s) are you seeing this problem on?"
    multiple: true
    options:
      - Android
      - ChromeOS
      - iOS
      - Linux
      - Mac
      - Windows
      - Other
    default: 0
  validations:
    required: true

- type: dropdown
  id: browsers
  attributes:
    label: Browser(s)
    description: "What browsers(s) are you seeing this problem on?"
    multiple: true
    options:
      - Arc
      - Chrome
      - Firefox
      - Internet (Galaxy)
      - Microsoft Edge
      - Opera
      - Safari
      - Other
    default: 0
  validations:
    required: true

- type: markdown
  attributes:
    - value: "_If you are using Internet Explorer, please switch to a modern browser before filling out this report._"

- type: textarea
  id: happened
  attributes:
    label: What happened
    description: "Tell us, step by step, how you got this behavior to happen."
  validations:
    required: true

- type: input
  id: expected
  attributes:
    label: Expected Behavior
    description: "Tell us, step by step, how you got this behavior to happen."
  validations:
    required: false

- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: "If possible, add screenshots of the bug."
  validations:
    required: false
